[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only-include = ["src/fire", "src/firce"]
sources = ["src"]

[project]
name = "xseciot"
version = "1.0.0"
description = "ML-based IoT intrusion detection with XAI & CE"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Seth Barrett", email = "sebarrett@augusta.edu" },
    { name = "Bradley Boswell", email = "brboswell@augusta.edu" },
    { name = "Swarnamugi Rajaganapathy", email = "swarnamugi@dfairlab.com" },
    { name = "Lin Li", email = "lli1@augusta.edu" },
    { name = "Gokila Dorai", email = "gdorai@augusta.edu" }
]
maintainers = [
    { name = "Seth Barrett", email = "sebarrett@augusta.edu" }
]
license = "unlicense"
license-files = ["LICEN[CS]E.*"]

dependencies = [
    "dask==2025.5.1",
    "joblib==1.5.1",
    "lime==0.2.0.1",
    "matplotlib==3.10.3",
    "numpy==2.1.3",
    "pandas==2.2.3",
    "scikit-learn==1.6.1",
    "scipy==1.15.3",
    "shap==0.47.2",
    "shortuuid>=1.0.13",
    "tensorflow==2.19.0",
    "toml>=0.10.2",
    "tqdm==4.67.1",
    "xgboost==3.0.2",
    "torch==2.8.0",
    "pydantic>=2.11.9",
    "cade-firce",
    "pyarrow>=23.0.1",
]

[dependency-groups]
dev = [
     "deptry>=0.25.1",
     "pytest>=8.3.5",
     "pytest-cov>=6.0.0",
     "ruff>=0.11.9",
     "twine>=6.1.0",
]

[project.scripts]
firce = "firce.cli:main"

[tool.uv]
default-groups = ["dev"]
package = true

[tool.uv.sources]
cade-firce = { git = "https://github.com/DFAIR-LAB-Augusta/CADE_FIRCE.git", rev = "dev" }

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = "--cov=src --cov-report=term-missing --cov-report=html"

[tool.deptry]
root = ["src"]

[tool.deptry.per_rule_ignores]
DEP002 = ["pyarrow"] # Used in dask
DEP003 = ["fire", "firce"]
